
/*


 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cc103;
import java.sql.*;
import java.awt.BorderLayout;
import javax.swing.JCheckBox;
import javax.swing.JRadioButton;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import java.awt.Image;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;


/**
 *
 * @author user
 */
public class Front extends javax.swing.JFrame {

    /**
     * Creates new form Front
     */
    public Front() {
        initComponents();
        Connect();
        
        
        Icon i = pizza.getIcon();
        ImageIcon icon = (ImageIcon)i;
        Image image = icon.getImage().getScaledInstance(pizza.getWidth(), pizza.getHeight(), Image.SCALE_SMOOTH);
        pizza.setIcon(new ImageIcon(image));
        
        Icon u = pizzaSize.getIcon();
        ImageIcon icon1 = (ImageIcon)u;
        Image image1 = icon1.getImage().getScaledInstance(pizzaSize.getWidth(), pizzaSize.getHeight(), Image.SCALE_SMOOTH);
        pizzaSize.setIcon(new ImageIcon(image1));
        
        Icon y = plusIcon.getIcon();
        ImageIcon icon2 = (ImageIcon)y;
        Image image2 = icon2.getImage().getScaledInstance(plusIcon.getWidth(), plusIcon.getHeight(), Image.SCALE_SMOOTH);
        plusIcon.setIcon(new ImageIcon(image2));
        
    }
    Connection con;
    PreparedStatement pst;
    ResultSet rs;
    
    public void Connect(){
            try{
                Class.forName("com.mysql.cj.jdbc.Driver");
                con = DriverManager.getConnection("jdbc:mysql://localhost/pizzaorder","root","");
        } catch (ClassNotFoundException ex){
                Logger.getLogger(Front.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Front.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        btnSize = new javax.swing.ButtonGroup();
        btnVariant = new javax.swing.ButtonGroup();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane10 = new javax.swing.JScrollPane();
        orderSum = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        amountTxt = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        receipt = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jToggleButton2 = new javax.swing.JToggleButton();
        jToggleButton1 = new javax.swing.JToggleButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        onionCheck = new javax.swing.JCheckBox();
        pepperCheck = new javax.swing.JCheckBox();
        blackCheck = new javax.swing.JCheckBox();
        greenCheck = new javax.swing.JCheckBox();
        cheeseCheck = new javax.swing.JCheckBox();
        hamcheeseRad = new javax.swing.JRadioButton();
        peperoniRad = new javax.swing.JRadioButton();
        smallBtn = new javax.swing.JRadioButton();
        mediumBtn = new javax.swing.JRadioButton();
        largeBtn = new javax.swing.JRadioButton();
        famBtn = new javax.swing.JRadioButton();
        pizza = new javax.swing.JLabel();
        pizzaSize = new javax.swing.JLabel();
        plusIcon = new javax.swing.JLabel();
        hawaiianRad = new javax.swing.JRadioButton();
        small = new javax.swing.JLabel();
        medium = new javax.swing.JLabel();
        famSize = new javax.swing.JLabel();
        large = new javax.swing.JLabel();
        checkOutBtn = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jButton3.setText("jButton3");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1000, 500));
        setMinimumSize(new java.awt.Dimension(1000, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 3, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("PAY HERE: ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 300, -1, 30));

        orderSum.setEditable(false);
        orderSum.setBackground(new java.awt.Color(231, 231, 178, 65));
        orderSum.setColumns(20);
        orderSum.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        orderSum.setForeground(new java.awt.Color(0, 0, 0));
        orderSum.setRows(5);
        jScrollPane10.setViewportView(orderSum);

        getContentPane().add(jScrollPane10, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 40, 490, 250));

        amountTxt.setBackground(new java.awt.Color(231, 231, 178));
        amountTxt.setForeground(new java.awt.Color(0, 0, 0));
        jScrollPane1.setViewportView(amountTxt);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 300, 100, 30));

        receipt.setEditable(false);
        receipt.setBackground(new java.awt.Color(231, 231, 178, 40));
        receipt.setColumns(20);
        receipt.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        receipt.setForeground(new java.awt.Color(0, 0, 0));
        receipt.setRows(5);
        jScrollPane2.setViewportView(receipt);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 340, 490, 190));

        jLabel6.setFont(new java.awt.Font("Comic Sans MS", 3, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("ORDER SUMMARY");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 10, -1, -1));

        jToggleButton2.setBackground(new java.awt.Color(246, 211, 115));
        jToggleButton2.setFont(new java.awt.Font("SansSerif", 3, 12)); // NOI18N
        jToggleButton2.setText("CHECK OUT");
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 300, 120, 30));

        jToggleButton1.setBackground(new java.awt.Color(246, 211, 115));
        jToggleButton1.setFont(new java.awt.Font("Tahoma", 1, 8)); // NOI18N
        jToggleButton1.setText("LOG IN - AUTHORIZED PERSONNEL ONLY");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 540, -1, -1));

        jPanel1.setBackground(new java.awt.Color(231, 231, 178));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 3, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("ADD - ONS!");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 110, 27));

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 3, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("SIZES!");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 70, -1));

        onionCheck.setBackground(new java.awt.Color(255, 255, 218));
        onionCheck.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        onionCheck.setForeground(new java.awt.Color(0, 0, 0));
        onionCheck.setText("ONIONS + 10");
        onionCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onionCheckActionPerformed(evt);
            }
        });
        jPanel1.add(onionCheck, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, -1, -1));

        pepperCheck.setBackground(new java.awt.Color(255, 255, 218));
        pepperCheck.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        pepperCheck.setForeground(new java.awt.Color(0, 0, 0));
        pepperCheck.setText("PEPPER + 10");
        pepperCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pepperCheckActionPerformed(evt);
            }
        });
        jPanel1.add(pepperCheck, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, -1, -1));

        blackCheck.setBackground(new java.awt.Color(255, 255, 218));
        blackCheck.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        blackCheck.setForeground(new java.awt.Color(0, 0, 0));
        blackCheck.setText("BLACK OLIVES + 10");
        blackCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blackCheckActionPerformed(evt);
            }
        });
        jPanel1.add(blackCheck, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, -1, -1));

        greenCheck.setBackground(new java.awt.Color(255, 255, 218));
        greenCheck.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        greenCheck.setForeground(new java.awt.Color(0, 0, 0));
        greenCheck.setText("GREEN PEPPERS + 10");
        greenCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                greenCheckActionPerformed(evt);
            }
        });
        jPanel1.add(greenCheck, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, -1, -1));

        cheeseCheck.setBackground(new java.awt.Color(255, 255, 218));
        cheeseCheck.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        cheeseCheck.setForeground(new java.awt.Color(0, 0, 0));
        cheeseCheck.setText("CHEESE + 15");
        cheeseCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cheeseCheckActionPerformed(evt);
            }
        });
        jPanel1.add(cheeseCheck, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 470, -1, -1));

        hamcheeseRad.setBackground(new java.awt.Color(255, 255, 218));
        btnSize.add(hamcheeseRad);
        hamcheeseRad.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        hamcheeseRad.setForeground(new java.awt.Color(0, 0, 0));
        hamcheeseRad.setText("HAM AND CHEESE ");
        hamcheeseRad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hamcheeseRadActionPerformed(evt);
            }
        });
        jPanel1.add(hamcheeseRad, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        peperoniRad.setBackground(new java.awt.Color(255, 255, 218));
        btnSize.add(peperoniRad);
        peperoniRad.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        peperoniRad.setForeground(new java.awt.Color(0, 0, 0));
        peperoniRad.setText("PEPERONI");
        peperoniRad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                peperoniRadActionPerformed(evt);
            }
        });
        jPanel1.add(peperoniRad, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        smallBtn.setBackground(new java.awt.Color(255, 255, 218));
        btnVariant.add(smallBtn);
        smallBtn.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        smallBtn.setForeground(new java.awt.Color(0, 0, 0));
        smallBtn.setSelected(true);
        smallBtn.setText("SMALL");
        smallBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smallBtnActionPerformed(evt);
            }
        });
        jPanel1.add(smallBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        mediumBtn.setBackground(new java.awt.Color(255, 255, 218));
        btnVariant.add(mediumBtn);
        mediumBtn.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        mediumBtn.setForeground(new java.awt.Color(0, 0, 0));
        mediumBtn.setText("MEDIUM");
        mediumBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mediumBtnActionPerformed(evt);
            }
        });
        jPanel1.add(mediumBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

        largeBtn.setBackground(new java.awt.Color(255, 255, 218));
        btnVariant.add(largeBtn);
        largeBtn.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        largeBtn.setForeground(new java.awt.Color(0, 0, 0));
        largeBtn.setText("LARGE");
        largeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                largeBtnActionPerformed(evt);
            }
        });
        jPanel1.add(largeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));

        famBtn.setBackground(new java.awt.Color(255, 255, 218));
        btnVariant.add(famBtn);
        famBtn.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        famBtn.setForeground(new java.awt.Color(0, 0, 0));
        famBtn.setText("FAMILY SIZE");
        famBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                famBtnActionPerformed(evt);
            }
        });
        jPanel1.add(famBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, -1, -1));

        pizza.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cc103/pizza (1).png"))); // NOI18N
        jPanel1.add(pizza, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 26, 27));

        pizzaSize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cc103/pizza (3).png"))); // NOI18N
        jPanel1.add(pizzaSize, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 26, 27));

        plusIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cc103/plus.png"))); // NOI18N
        jPanel1.add(plusIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 26, 27));

        hawaiianRad.setBackground(new java.awt.Color(255, 255, 218));
        btnSize.add(hawaiianRad);
        hawaiianRad.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        hawaiianRad.setForeground(new java.awt.Color(0, 0, 0));
        hawaiianRad.setText("HAWAIIAN ");
        hawaiianRad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hawaiianRadActionPerformed(evt);
            }
        });
        jPanel1.add(hawaiianRad, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        small.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        small.setForeground(new java.awt.Color(0, 0, 0));
        small.setText("0");
        jPanel1.add(small, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, 81, -1));

        medium.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        medium.setForeground(new java.awt.Color(0, 0, 0));
        medium.setText("0");
        jPanel1.add(medium, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 81, -1));

        famSize.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        famSize.setForeground(new java.awt.Color(0, 0, 0));
        famSize.setText("0");
        jPanel1.add(famSize, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 270, 50, -1));

        large.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        large.setForeground(new java.awt.Color(0, 0, 0));
        large.setText("0");
        jPanel1.add(large, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, 46, -1));

        checkOutBtn.setBackground(new java.awt.Color(246, 211, 115));
        checkOutBtn.setFont(new java.awt.Font("SansSerif", 3, 12)); // NOI18N
        checkOutBtn.setText("CREATE ORDER");
        checkOutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkOutBtnActionPerformed(evt);
            }
        });
        jPanel1.add(checkOutBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 500, -1, -1));

        jLabel7.setFont(new java.awt.Font("Comic Sans MS", 3, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("VARIANT!");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        jButton2.setBackground(new java.awt.Color(246, 211, 115));
        jButton2.setFont(new java.awt.Font("SansSerif", 3, 12)); // NOI18N
        jButton2.setText("CLEAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 500, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 280, 540));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cc103/bacground.png"))); // NOI18N
        jLabel1.setOpaque(true);
        jLabel1.setPreferredSize(new java.awt.Dimension(960, 568));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 990, 590));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed
    public String spaces(int x){
        String spacing = "";
        if (x == 5){
            spacing = "\n";
        }else if (x == 4){
            spacing = "\n\n";
        }else if (x == 3){
            spacing = "\n\n\n";
        }else if (x == 2){
            spacing = "\n\n\n\n";
        }else if (x == 1){
            spacing = "\n\n\n\n\n";
        }else{
            spacing = "\n\n\t*NO ADD-ONS SELECTED*\n\n\n\n";
        }
        return spacing;
    }
    private void hawaiianRadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hawaiianRadActionPerformed
        // TODO add your handling code here:
        
        checkOutBtn.setEnabled(true);

        small.setText("69");
        medium.setText("79");
        large.setText("89");
        famSize.setText("99");
        
   
        
        
   
    }//GEN-LAST:event_hawaiianRadActionPerformed

    private void famBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_famBtnActionPerformed
        // TODO add your handling code here:

        
    }//GEN-LAST:event_famBtnActionPerformed

    private void largeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_largeBtnActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_largeBtnActionPerformed

    private void mediumBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mediumBtnActionPerformed
        // TODO add your handling code here:

       
    }//GEN-LAST:event_mediumBtnActionPerformed

    private void smallBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smallBtnActionPerformed
        // TODO add your handling code here:

        
    }//GEN-LAST:event_smallBtnActionPerformed

    private void peperoniRadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_peperoniRadActionPerformed
        // TODO add your handling code here:
        checkOutBtn.setEnabled(true);
        small.setText("89");
        medium.setText("99");
        large.setText("109");
        famSize.setText("118");
    }//GEN-LAST:event_peperoniRadActionPerformed

    private void hamcheeseRadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hamcheeseRadActionPerformed
        // TODO add your handling code here:
        checkOutBtn.setEnabled(true);
        small.setText("79");
        medium.setText("89");
        large.setText("99");
        famSize.setText("109");

    }//GEN-LAST:event_hamcheeseRadActionPerformed

    private void cheeseCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cheeseCheckActionPerformed
        // TODO add your handling code here:

        
    }//GEN-LAST:event_cheeseCheckActionPerformed

    private void greenCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_greenCheckActionPerformed
        // TODO add your handling code here:

        
    }//GEN-LAST:event_greenCheckActionPerformed

    private void blackCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blackCheckActionPerformed
        // TODO add your handling code here:

     
    }//GEN-LAST:event_blackCheckActionPerformed

    private void pepperCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pepperCheckActionPerformed
        // TODO add your handling code here:

      
    }//GEN-LAST:event_pepperCheckActionPerformed

    private void onionCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onionCheckActionPerformed
        // TODO add your handling code here:

       
    }//GEN-LAST:event_onionCheckActionPerformed

    private void checkOutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkOutBtnActionPerformed
        // TODO add your handling code here:
        
        String variant = "";
        String addOns = "";
        String size = "";
        int items = 0;
        int price = 0;
        
        // variants
        if (hawaiianRad.isSelected()== true){
            variant = hawaiianRad.getText();
        }
        if (hamcheeseRad.isSelected()== true){
            variant = hamcheeseRad.getText();
        }
        if (peperoniRad.isSelected()== true){
            variant = peperoniRad.getText();
        }
        
        
        //sizes
        
        if (smallBtn.isSelected()== true){
            size = smallBtn.getText();
            price = Integer.parseInt(small.getText());
        }
        if (mediumBtn.isSelected()== true){
            size = mediumBtn.getText();
            price = Integer.parseInt(medium.getText());
        }
        if (largeBtn.isSelected()== true){
            size = largeBtn.getText();
            price = Integer.parseInt(large.getText());
        }
        if (famBtn.isSelected()== true){
            size = famBtn.getText();
            price = Integer.parseInt(famSize.getText());
        }
        if(onionCheck.isSelected()){
            addOns += onionCheck.getText() + "\n\t";
            price += 10;
            items += 1;
        }
        if(pepperCheck.isSelected()){
            
            addOns += pepperCheck.getText() + "\n\t";
            price += 10;
            items += 1;
        }
        if(blackCheck.isSelected()){
            addOns += blackCheck.getText() + "\n\t";
            price += 10;
            items += 1;
        }
        if(greenCheck.isSelected()){
            addOns += greenCheck.getText() + "\n\t";
            price += 10;
            items += 1;
        }
        if(cheeseCheck.isSelected()){
            addOns += cheeseCheck.getText() + "\n\t";
            price += 15;
            items += 1;
        }
        
        orderSum.setText(" PIZZA VARIANT : " + variant +"\n\n PIZZA SIZE : " +size+ "\n\n ADD ONS : \n\t"+addOns+spaces(items)+"TOTAL PRICE : "+price+ " PESOS");
        
    
        
    }//GEN-LAST:event_checkOutBtnActionPerformed

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
        // TODO add your handling code here:
        String addOns = "";
        String size = "";
        int price = 0;
        
        if (smallBtn.isSelected() == true ){
            size = smallBtn.getText();
            price = Integer.parseInt(small.getText());
        }
        if (mediumBtn.isSelected() == true ){
            size = mediumBtn.getText();
            price = Integer.parseInt(medium.getText());
        }
        if (largeBtn.isSelected() == true ){
            size = largeBtn.getText();
            price = Integer.parseInt(large.getText());
        }
        if (famBtn.isSelected() == true ){
            size = famBtn.getText();
            price = Integer.parseInt(famSize.getText());
        }
        if (onionCheck.isSelected() == true){
            addOns += onionCheck.getText()+"\n\n";
            price += 10.00;
        }
        if (pepperCheck.isSelected() == true){
            addOns += pepperCheck.getText()+"\n\n";
            price += 10.00;
        }
        if (blackCheck.isSelected() == true){
            addOns += blackCheck.getText()+"\n\n";
            price += 10.00;
        }
        if (greenCheck.isSelected() == true){
            addOns += greenCheck.getText()+"\n\n"; 
            price += 10.00;
        }
        if (cheeseCheck.isSelected() == true){
            addOns += cheeseCheck.getText()+"\n\n";
            price += 15.00;
        }
        double amount = Double.parseDouble(amountTxt.getText());
        double change = amount - price;
        
        if (change < 0){
            receipt.setText("\nAMOUNT PAID : "+amount+ "\n\nTOTAL PRICE : "+ price+ "\n\nCHANGE : "+change+"\n\n\t***INVALID ORDER***");
        }else {
            receipt.setText("\nAMOUNT PAID : "+amount+ "\n\nTOTAL PRICE : "+ price+ "\n\nCHANGE : "+change);
        }
        String variant = "";
        
        if (hawaiianRad.isSelected()){
            variant = hawaiianRad.getText();
        }else if (hamcheeseRad.isSelected()){
            variant = hamcheeseRad.getText();
        }else if (peperoniRad.isSelected()){
            variant = peperoniRad.getText();
        }
        
        
        try {
            PreparedStatement pst = con.prepareStatement("INSERT INTO orders(variant, size, price, `add ons`)VALUES(?, ?, ?, ?)");
            pst.setString(1,variant);
            pst.setString(2,size);
            pst.setInt(3, (int) price);
            pst.setString(4, addOns.equals("") ? "no" : "yes");
            
            int rowsInserted = pst.executeUpdate();
            
            if (rowsInserted > 0){
                JOptionPane.showMessageDialog(this,"Record Added Successfully!");
                
            }else{JOptionPane.showMessageDialog(this,"Record Insertion Failed!");
            
            }
        } catch (SQLException ex) {
            Logger.getLogger(Front.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jToggleButton2ActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:
        loginPage ap=new loginPage();
                ap.setVisible(true);
                this.dispose();
        
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        btnSize.clearSelection();
        smallBtn.setSelected(true);
        
        if (onionCheck.isSelected()==true){
            onionCheck.setSelected(false);
        }
        if (pepperCheck.isSelected()==true){
            pepperCheck.setSelected(false);
        }
        if (blackCheck.isSelected()==true){
            blackCheck.setSelected(false);
        }
        if (greenCheck.isSelected()==true){
            greenCheck.setSelected(false);
        }
        if (cheeseCheck.isSelected()==true){
            cheeseCheck.setSelected(false);
        }
        
        checkOutBtn.setEnabled(false);
        amountTxt.setText(null);
        orderSum.setText("");
        receipt.setText("");
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Front.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Front.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Front.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Front.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Front().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextPane amountTxt;
    private javax.swing.JCheckBox blackCheck;
    private javax.swing.ButtonGroup btnSize;
    private javax.swing.ButtonGroup btnVariant;
    private javax.swing.JButton checkOutBtn;
    private javax.swing.JCheckBox cheeseCheck;
    private javax.swing.JRadioButton famBtn;
    private javax.swing.JLabel famSize;
    private javax.swing.JCheckBox greenCheck;
    private javax.swing.JRadioButton hamcheeseRad;
    private javax.swing.JRadioButton hawaiianRad;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JLabel large;
    private javax.swing.JRadioButton largeBtn;
    private javax.swing.JLabel medium;
    private javax.swing.JRadioButton mediumBtn;
    private javax.swing.JCheckBox onionCheck;
    private javax.swing.JTextArea orderSum;
    private javax.swing.JRadioButton peperoniRad;
    private javax.swing.JCheckBox pepperCheck;
    private javax.swing.JLabel pizza;
    private javax.swing.JLabel pizzaSize;
    private javax.swing.JLabel plusIcon;
    private javax.swing.JTextArea receipt;
    private javax.swing.JLabel small;
    private javax.swing.JRadioButton smallBtn;
    // End of variables declaration//GEN-END:variables
}
